/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sorteioacamps;

/**
 *
 * @author Lucas
 */
public class Iniciar extends javax.swing.JFrame {

     SortearNumero sort_numb = new SortearNumero();
     SortearTarefa sort_tarefa = new SortearTarefa();
    
    public Iniciar() {
        initComponents();
        //verificar_janela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        sortear_numero = new javax.swing.JButton();
        sortear_pessoa = new javax.swing.JButton();
        label_titulo = new javax.swing.JLabel();
        label_igreja = new javax.swing.JLabel();
        label_versao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sorteio Acamps");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        sortear_numero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorteioacamps/imagens/sortear_brinde_v.jpg"))); // NOI18N
        sortear_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortear_numeroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -7;
        gridBagConstraints.ipady = -7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 280, 0, 0);
        getContentPane().add(sortear_numero, gridBagConstraints);

        sortear_pessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorteioacamps/imagens/sortear_tarefa_v.jpg"))); // NOI18N
        sortear_pessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortear_pessoaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = -7;
        gridBagConstraints.ipady = -7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 280, 0, 0);
        getContentPane().add(sortear_pessoa, gridBagConstraints);

        label_titulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        label_titulo.setForeground(new java.awt.Color(0, 133, 178));
        label_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_titulo.setText("Sorteio de Tarefas ou Brindes");
        label_titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipadx = -46;
        gridBagConstraints.ipady = 57;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 80, 0, 61);
        getContentPane().add(label_titulo, gridBagConstraints);

        label_igreja.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        label_igreja.setForeground(new java.awt.Color(0, 133, 178));
        label_igreja.setText("Primeira Igreja Batista Bíblica no Novo Gama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = -72;
        gridBagConstraints.ipady = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 80, 0, 0);
        getContentPane().add(label_igreja, gridBagConstraints);

        label_versao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label_versao.setForeground(new java.awt.Color(0, 133, 178));
        label_versao.setText("Versão 1.0 - 09/02/2017");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 10, 5, 0);
        getContentPane().add(label_versao, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sortear_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortear_numeroActionPerformed
        
        sort_numb.setVisible(true);
       
    }//GEN-LAST:event_sortear_numeroActionPerformed

    private void sortear_pessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortear_pessoaActionPerformed
        
        sort_tarefa.setVisible(true);
        
    }//GEN-LAST:event_sortear_pessoaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Iniciar().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_igreja;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_versao;
    private javax.swing.JButton sortear_numero;
    private javax.swing.JButton sortear_pessoa;
    // End of variables declaration//GEN-END:variables
}
