/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sorteioacamps;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;

/**
 *
 * @author Lucas
 */
public class Iniciar extends javax.swing.JFrame {

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    int screenWidth = (int)screenSize.getWidth();
    int screenHeight = (int)screenSize.getHeight();
    SortearNumero sort_numb = new SortearNumero();
    SortearTarefa sort_tarefa = new SortearTarefa();
    
    public Iniciar() {
        initComponents();
        //verificar_janela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        label_titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sortear_pessoa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        sortear_numero = new javax.swing.JButton();
        label_igreja = new javax.swing.JLabel();
        label_versao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sorteio Acamps");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new java.awt.GridLayout(6, 1, 0, 15));
        getContentPane().add(jPanel3);

        label_titulo.setFont(new java.awt.Font("Arial", 1, screenHeight/15));
        label_titulo.setForeground(new java.awt.Color(0, 133, 178));
        label_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_titulo.setText("Sorteio de Tarefas ou Brindes");
        label_titulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_titulo.setMaximumSize(new java.awt.Dimension(screenWidth/2, 36));
        label_titulo.setMinimumSize(new java.awt.Dimension(800, 36));
        label_titulo.setPreferredSize(new java.awt.Dimension(screenWidth/2, 36));
        getContentPane().add(label_titulo);

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        sortear_pessoa.setBackground(new java.awt.Color(242, 242, 242));
        sortear_pessoa.setFont(new java.awt.Font("Liberation Sans", 0, screenHeight/30));
        sortear_pessoa.setText("Sortear para Tarefas");
        sortear_pessoa.setToolTipText("");
        sortear_pessoa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sortear_pessoa.setBorderPainted(false);
        sortear_pessoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortear_pessoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sortear_pessoa.setMaximumSize(new java.awt.Dimension(screenWidth/2, screenHeight/6));
        sortear_pessoa.setMinimumSize(new java.awt.Dimension(screenWidth/2, screenHeight/6));
        sortear_pessoa.setPreferredSize(new java.awt.Dimension(screenWidth/2, screenHeight/6));
        sortear_pessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortear_pessoaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(sortear_pessoa, gridBagConstraints);

        getContentPane().add(jPanel2);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        sortear_numero.setBackground(new java.awt.Color(242, 242, 242));
        sortear_numero.setFont(new java.awt.Font("Liberation Sans", 0, screenHeight/30));
        sortear_numero.setText("Sortear para Brindes");
        sortear_numero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sortear_numero.setBorderPainted(false);
        sortear_numero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortear_numero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sortear_numero.setMaximumSize(new java.awt.Dimension(screenWidth/2, screenHeight/6));
        sortear_numero.setMinimumSize(new java.awt.Dimension(screenWidth/2, screenHeight/6));
        sortear_numero.setPreferredSize(new java.awt.Dimension(screenWidth/2, screenHeight/6));
        sortear_numero.setVerifyInputWhenFocusTarget(false);
        sortear_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortear_numeroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(sortear_numero, gridBagConstraints);

        getContentPane().add(jPanel1);

        label_igreja.setFont(new java.awt.Font("Arial", 1, screenHeight/20));
        label_igreja.setForeground(new java.awt.Color(0, 133, 178));
        label_igreja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_igreja.setText("Primeira Igreja Batista Bíblica no Novo Gama");
        label_igreja.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        label_igreja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_igreja.setMaximumSize(new java.awt.Dimension((int)screenWidth/2, 36));
        label_igreja.setPreferredSize(new java.awt.Dimension((int)screenWidth/2, 36));
        label_igreja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(label_igreja);

        label_versao.setFont(new java.awt.Font("Arial", 1, screenHeight/40));
        label_versao.setForeground(new java.awt.Color(0, 133, 178));
        label_versao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_versao.setText("Versão 1.0 - 09/02/2017");
        label_versao.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        label_versao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        label_versao.setMaximumSize(new java.awt.Dimension(160, 30));
        label_versao.setMinimumSize(new java.awt.Dimension(160, 30));
        getContentPane().add(label_versao);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sortear_pessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortear_pessoaActionPerformed

        sort_tarefa.setVisible(true);

    }//GEN-LAST:event_sortear_pessoaActionPerformed

    private void sortear_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortear_numeroActionPerformed

        sort_numb.setVisible(true);

    }//GEN-LAST:event_sortear_numeroActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Iniciar().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_igreja;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_versao;
    private javax.swing.JButton sortear_numero;
    private javax.swing.JButton sortear_pessoa;
    // End of variables declaration//GEN-END:variables
}
