/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sorteioacamps;

/**
 *
 * @author Lucas
 */
public class Iniciar extends javax.swing.JFrame {

     SortearNumero sort_numb = new SortearNumero();
    
    public Iniciar() {
        initComponents();
        //verificar_janela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortear_numero = new javax.swing.JButton();
        sortear_pessoa = new javax.swing.JButton();
        label_titulo = new javax.swing.JLabel();
        label_igreja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sorteio Acamps");
        setLocation(new java.awt.Point(683, 384));
        setResizable(false);

        sortear_numero.setText("Sortear Número");
        sortear_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortear_numeroActionPerformed(evt);
            }
        });

        sortear_pessoa.setText("Sortear Pessoa");
        sortear_pessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortear_pessoaActionPerformed(evt);
            }
        });

        label_titulo.setText("Sorteio de Tarefas ou Brindes");
        label_titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        label_igreja.setText("Primeira Igreja Batista Bíblica no Novo Gama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_titulo)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(label_igreja))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sortear_numero)
                            .addComponent(sortear_pessoa))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(label_titulo)
                .addGap(61, 61, 61)
                .addComponent(sortear_numero)
                .addGap(18, 18, 18)
                .addComponent(sortear_pessoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(label_igreja)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sortear_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortear_numeroActionPerformed
        
        sort_numb.setVisible(true);
       
    }//GEN-LAST:event_sortear_numeroActionPerformed

    private void sortear_pessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortear_pessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortear_pessoaActionPerformed

//    private void verificar_janela(){
//        
//        if(sort_numb.isEnabled()){
//            sortear_pessoa.setEnabled(false);
//            sortear_numero.setEnabled(false);
//        } else {
//            sortear_pessoa.setEnabled(true);
//            sortear_pessoa.setEnabled(true);
//        }
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Iniciar().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_igreja;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JButton sortear_numero;
    private javax.swing.JButton sortear_pessoa;
    // End of variables declaration//GEN-END:variables
}
