/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sorteioacamps;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.IOException;


/**
 *
 * @author Lucas
 */
public final class MainMenu extends javax.swing.JFrame {

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    int screenWidth = (int)screenSize.getWidth();
    int screenHeight = (int)screenSize.getHeight();
    RaffleANumber sort_numb = new RaffleANumber();
    RaffleMultNumbers sort_tarefa = new RaffleMultNumbers();
    AllRecords allRecords = new AllRecords();

    public MainMenu() throws IOException, FontFormatException {
        initComponents();
        applyTextFonts(screenWidth, screenHeight);
        Color customColor = new Color(255, 255, 255);
        getContentPane().setBackground(customColor);
        addComponentListener(new ComponentAdapter(){
                @Override
                public void componentResized(ComponentEvent e){
                    int newScreenWidth = getWidth();
                    int newScreenHeight = getHeight();
                    applyTextFonts(newScreenWidth, newScreenHeight);
                }
            }
        );
        //verificar_janela();
    }

    private void applyTextFonts(int screenWidth, int screenHeight){
        int averageScreenSize = (int)(screenWidth + screenHeight) / 2;
        String shadowKGHappy = "fonts/KGHAPPY.ttf";
        String solidKGHappy = "fonts/KGHAPPYSolid.ttf";
        text1.setFont(CustomFont.loadFont(shadowKGHappy, Font.PLAIN, averageScreenSize/27));
        text2.setFont(CustomFont.loadFont(shadowKGHappy, Font.PLAIN, averageScreenSize/27));
        text3.setFont(CustomFont.loadFont(shadowKGHappy, Font.PLAIN, averageScreenSize/47));
        allRecordsButton.setFont(CustomFont.loadFont(solidKGHappy, Font.PLAIN, averageScreenSize/37));
        raffleANumbers.setFont(CustomFont.loadFont(solidKGHappy, Font.PLAIN, averageScreenSize/37));
        raffleMultNumbers.setFont(CustomFont.loadFont(solidKGHappy, Font.PLAIN, averageScreenSize/37));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        raffleANumbers = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        raffleMultNumbers = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        allRecordsButton = new javax.swing.JButton();
        text2 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sorteio Acamps");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new java.awt.GridLayout(7, 1, 0, 15));

        jPanel3.setOpaque(false);
        getContentPane().add(jPanel3);

        text1.setFont(new java.awt.Font("Mandali", 1, screenHeight/15));
        text1.setForeground(new java.awt.Color(0, 133, 178));
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("Sorteio de Tarefas ou Brindes");
        text1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        text1.setMaximumSize(new java.awt.Dimension(screenWidth/2, 36));
        text1.setMinimumSize(new java.awt.Dimension(800, 36));
        text1.setPreferredSize(new java.awt.Dimension(screenWidth/2, 36));
        getContentPane().add(text1);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        raffleANumbers.setBackground(new java.awt.Color(202, 202, 202));
        raffleANumbers.setFont(new java.awt.Font("Liberation Sans", 0, screenHeight/30));
        raffleANumbers.setText("Sorteio Único");
        raffleANumbers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        raffleANumbers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        raffleANumbers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        raffleANumbers.setVerifyInputWhenFocusTarget(false);
        raffleANumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raffleANumbersActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(raffleANumbers, gridBagConstraints);

        getContentPane().add(jPanel1);

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        raffleMultNumbers.setBackground(new java.awt.Color(202, 202, 202));
        raffleMultNumbers.setFont(new java.awt.Font("Liberation Sans", 0, screenHeight/30));
        raffleMultNumbers.setText("Sortear Vários");
        raffleMultNumbers.setToolTipText("");
        raffleMultNumbers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        raffleMultNumbers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        raffleMultNumbers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        raffleMultNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raffleMultNumbersActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(raffleMultNumbers, gridBagConstraints);

        getContentPane().add(jPanel2);

        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        allRecordsButton.setBackground(new java.awt.Color(202, 202, 202));
        allRecordsButton.setFont(new java.awt.Font("Liberation Sans", 0, screenHeight/30));
        allRecordsButton.setText("Ver Registros");
        allRecordsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        allRecordsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        allRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allRecordsButtonActionPerformed(evt);
            }
        });
        jPanel4.add(allRecordsButton, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel4);

        text2.setFont(new java.awt.Font("Arial", 1, screenHeight/20));
        text2.setForeground(new java.awt.Color(0, 133, 178));
        text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        text2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        text2.setMaximumSize(new java.awt.Dimension((int)screenWidth/2, 36));
        text2.setPreferredSize(new java.awt.Dimension((int)screenWidth/2, 36));
        text2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(text2);

        text3.setFont(new java.awt.Font("Arial", 1, screenHeight/40));
        text3.setForeground(new java.awt.Color(0, 133, 178));
        text3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        text3.setText("Versão 2.0.1 - 07/02/2023");
        text3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        text3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        text3.setMaximumSize(new java.awt.Dimension(160, 30));
        text3.setMinimumSize(new java.awt.Dimension(160, 30));
        getContentPane().add(text3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raffleMultNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raffleMultNumbersActionPerformed

        sort_tarefa.setVisible(true);

    }//GEN-LAST:event_raffleMultNumbersActionPerformed

    private void raffleANumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raffleANumbersActionPerformed

        sort_numb.setVisible(true);

    }//GEN-LAST:event_raffleANumbersActionPerformed

    private void allRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allRecordsButtonActionPerformed
        allRecords.setVisible(true);
        allRecords.updateRecords();
    }//GEN-LAST:event_allRecordsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allRecordsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton raffleANumbers;
    private javax.swing.JButton raffleMultNumbers;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    // End of variables declaration//GEN-END:variables
}
