/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sorteioacamps;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Collections;
import static sorteioacamps.Utils.ParseRaffledNumberToString;

/**
 *
 * @author Lucas
 */
public class RaffleANumber extends javax.swing.JFrame {

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    int screenWidth = (int)screenSize.getWidth();
    int screenHeight = (int)screenSize.getHeight();
    Raffle raffle = new Raffle();
    Timer t;
    int winksCount = 0;
    int maxWinks = 5;
    int maxTime = 100;
    private NumberRecordManager recordManager = new NumberRecordManager();
    private ArrayList<NumberRecord> records;

    public int WinkAJLabel(javax.swing.JLabel jlabel, int maxWinks, int winksCount){
        if (jlabel.isVisible() == true) {
            jlabel.setVisible(false);
        }else{
            jlabel.setVisible(true);
        }
        winksCount++;
        return winksCount;
    }

    private int[] ValidateReceivedNumbersRange(javax.swing.JTextField jTextFieldNumMax, javax.swing.JTextField jTextFieldNumMin, javax.swing.JLabel jLabelValidationError){
        int numMax = 0;
        int numMin = 0;
        try{
            numMax = Integer.parseInt(jTextFieldNumMax.getText());
            numMin = Integer.parseInt(jTextFieldNumMin.getText());
        } catch(NumberFormatException ex) {
            jLabelValidationError.setText("Os campos devem conter somente números inteiros!");
            return null;
        }
        if(numMin > numMax){
            jLabelValidationError.setText("Os inteiros devem ser inseridos em forma crescente!");
            return null;
        }
        int[] values = {numMin, numMax};
        return values;
    }

    public RaffleANumber() {
        records = recordManager.readRecords();
        initComponents();
        text4.setText("???");
        t = new javax.swing.Timer(maxTime, (ActionEvent e) -> {
            String selectedOption = recordManager.translateOption((String) raffledTo.getSelectedItem());
            int[] values = ValidateReceivedNumbersRange(maximumNumber, minimalNumber, errorLabel);
            if(values != null){
                if(winksCount < maxWinks){
                    winksCount = WinkAJLabel(text4, maxWinks, winksCount);
                } else {
                    t.stop();
                    text4.setVisible(true);
                    winksCount = maxWinks;
                    ArrayList<Integer> numbersToRaffleByOption = recordManager.returnAllNumbersCanRaffleByOption(
                            selectedOption,
                            records,
                            values[0],
                            values[1]
                    );
                    Collections.shuffle(numbersToRaffleByOption);
                    int raffledNumber = numbersToRaffleByOption.get(0);
                    String parsedRaffledNumber = ParseRaffledNumberToString(raffledNumber);
                    text4.setText(parsedRaffledNumber);
                }
            } 
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        minimalNumber = new javax.swing.JTextField();
        text2 = new javax.swing.JLabel();
        maximumNumber = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();
        text5 = new javax.swing.JLabel();
        raffledTo = new javax.swing.JComboBox<>();
        text3 = new javax.swing.JLabel();
        text4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cleanButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        raffleButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 25), new java.awt.Dimension(15, 25), new java.awt.Dimension(15, 25));
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sortear um Número");
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        setLocation(new java.awt.Point(600, 300));
        getContentPane().setLayout(new java.awt.GridLayout(5, 0, 0, 15));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        text1.setFont(new java.awt.Font("Arial Black", 0, screenHeight/15));
        text1.setForeground(new java.awt.Color(0, 133, 178));
        text1.setText("Sortear número entre");
        jPanel1.add(text1, new java.awt.GridBagConstraints());

        minimalNumber.setFont(new java.awt.Font("Arial Black", 0, screenHeight/15));
        minimalNumber.setForeground(new java.awt.Color(0, 133, 178));
        minimalNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minimalNumber.setText("0");
        minimalNumber.setMaximumSize(new java.awt.Dimension(screenWidth/10, screenHeight/15));
        minimalNumber.setMinimumSize(new java.awt.Dimension(screenWidth/10, screenHeight/15));
        minimalNumber.setPreferredSize(new java.awt.Dimension(screenWidth/10, screenHeight/15));
        minimalNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimalNumberActionPerformed(evt);
            }
        });
        jPanel1.add(minimalNumber, new java.awt.GridBagConstraints());

        text2.setFont(new java.awt.Font("Arial Black", 0, screenHeight/15));
        text2.setForeground(new java.awt.Color(0, 133, 178));
        text2.setText("e");
        jPanel1.add(text2, new java.awt.GridBagConstraints());

        maximumNumber.setFont(new java.awt.Font("Arial Black", 0, screenHeight/15));
        maximumNumber.setForeground(new java.awt.Color(0, 133, 178));
        maximumNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maximumNumber.setText("0");
        maximumNumber.setMaximumSize(new java.awt.Dimension(screenWidth/10, screenHeight/15));
        maximumNumber.setMinimumSize(new java.awt.Dimension(screenWidth/10, screenHeight/15));
        maximumNumber.setPreferredSize(new java.awt.Dimension(screenWidth/10, screenHeight/15));
        maximumNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maximumNumberActionPerformed(evt);
            }
        });
        jPanel1.add(maximumNumber, new java.awt.GridBagConstraints());

        errorLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel1.add(errorLabel, gridBagConstraints);

        text5.setFont(new java.awt.Font("Arial Black", 0, screenHeight/15));
        text5.setForeground(new java.awt.Color(0, 133, 178));
        text5.setText("para receber");
        jPanel1.add(text5, new java.awt.GridBagConstraints());

        raffledTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nada", "Tarefa", "Brinde", "Outro" }));
        raffledTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raffledToActionPerformed(evt);
            }
        });
        jPanel1.add(raffledTo, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1);

        text3.setFont(new java.awt.Font("Arial Black", 0, screenHeight/15));
        text3.setForeground(new java.awt.Color(0, 133, 178));
        text3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text3.setText("Número Sorteado:");
        text3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(text3);

        text4.setFont(new java.awt.Font("Showcard Gothic", 1, screenHeight/7));
        text4.setForeground(new java.awt.Color(0, 133, 178));
        text4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text4.setText("???");
        getContentPane().add(text4);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        cleanButton.setBackground(new java.awt.Color(242, 242, 242));
        cleanButton.setFont(new java.awt.Font("Liberation Sans", 0, screenHeight/40));
        cleanButton.setText("Limpar");
        cleanButton.setToolTipText("");
        cleanButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cleanButton.setBorderPainted(false);
        cleanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cleanButton.setEnabled(false);
        cleanButton.setMaximumSize(new java.awt.Dimension(screenWidth/10, screenHeight/40));
        cleanButton.setMinimumSize(new java.awt.Dimension(screenWidth/10, screenHeight/40));
        cleanButton.setPreferredSize(new java.awt.Dimension(screenWidth/10, screenHeight/40));
        cleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButtonActionPerformed(evt);
            }
        });
        jPanel3.add(cleanButton, new java.awt.GridBagConstraints());
        jPanel3.add(filler1, new java.awt.GridBagConstraints());

        raffleButton.setBackground(new java.awt.Color(242, 242, 242));
        raffleButton.setFont(new java.awt.Font("Liberation Sans", 0, screenHeight/40));
        raffleButton.setText("Sortear");
        raffleButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        raffleButton.setBorderPainted(false);
        raffleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        raffleButton.setMaximumSize(new java.awt.Dimension(screenWidth/10, screenHeight/40));
        raffleButton.setMinimumSize(new java.awt.Dimension(screenWidth/10, screenHeight/40));
        raffleButton.setPreferredSize(new java.awt.Dimension(screenWidth/10, screenHeight/40));
        raffleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raffleButtonActionPerformed(evt);
            }
        });
        jPanel3.add(raffleButton, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel3);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(filler2);

        backButton.setBackground(new java.awt.Color(242, 242, 242));
        backButton.setFont(new java.awt.Font("Liberation Sans", 0, screenHeight/40));
        backButton.setText("Voltar");
        backButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton.setBorderPainted(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.setMaximumSize(new java.awt.Dimension(screenWidth/10, screenHeight/40));
        backButton.setMinimumSize(new java.awt.Dimension(screenWidth/10, screenHeight/40));
        backButton.setPreferredSize(new java.awt.Dimension(screenWidth/10, screenHeight/40));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel2.add(backButton);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimalNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimalNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimalNumberActionPerformed

    private void maximumNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maximumNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maximumNumberActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        this.setVisible(false);
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
        text4.setText("???");
        errorLabel.setText("");
        raffleButton.setEnabled(true);
        cleanButton.setEnabled(false);
    }//GEN-LAST:event_cleanButtonActionPerformed

    private void raffleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raffleButtonActionPerformed
        winksCount = 0;
        t.setInitialDelay(0);
        t.start();
        cleanButton.setEnabled(true);
        raffleButton.setEnabled(false);
    }//GEN-LAST:event_raffleButtonActionPerformed

    private void raffledToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raffledToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raffledToActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RaffleANumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RaffleANumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RaffleANumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RaffleANumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RaffleANumber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton cleanButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField maximumNumber;
    private javax.swing.JTextField minimalNumber;
    private javax.swing.JButton raffleButton;
    private javax.swing.JComboBox<String> raffledTo;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    // End of variables declaration//GEN-END:variables
}
