/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sorteioacamps;

/**
 *
 * @author Lucas
 */
public class SortearTarefa extends javax.swing.JFrame {

    /**
     * Creates new form SortearTarefa
     */
    public SortearTarefa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortear_label = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        numeros_label = new javax.swing.JLabel();
        sortear_button = new javax.swing.JButton();
        limpar_button = new javax.swing.JButton();
        sort_number_1 = new javax.swing.JLabel();
        sort_number_2 = new javax.swing.JLabel();
        sort_number_3 = new javax.swing.JLabel();
        sort_number_4 = new javax.swing.JLabel();
        sort_number_5 = new javax.swing.JLabel();
        sort_number_6 = new javax.swing.JLabel();
        sort_number_7 = new javax.swing.JLabel();
        sort_number_8 = new javax.swing.JLabel();
        sort_number_9 = new javax.swing.JLabel();
        sort_number_10 = new javax.swing.JLabel();
        grade_sorteio = new javax.swing.JLabel();
        numeros_sorteados_label = new javax.swing.JLabel();
        voltar_button = new javax.swing.JButton();
        erro_variável = new javax.swing.JLabel();
        sortear_tarefa_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sortear Tarefa");
        setLocation(new java.awt.Point(600, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sortear_label.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        sortear_label.setForeground(new java.awt.Color(0, 133, 178));
        sortear_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sortear_label.setText("Sortear");
        getContentPane().add(sortear_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 100, -1));

        jTextField1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 133, 178));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 50, 40));

        numeros_label.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        numeros_label.setForeground(new java.awt.Color(0, 133, 178));
        numeros_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeros_label.setText("NUMEROS SORTEADOS:");
        getContentPane().add(numeros_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 460, -1));

        sortear_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorteioacamps/imagens/sortear_v2.jpg"))); // NOI18N
        sortear_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortear_button.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sorteioacamps/imagens/sortear_v.jpg"))); // NOI18N
        getContentPane().add(sortear_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 90, 30));

        limpar_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorteioacamps/imagens/limpar_v.jpg"))); // NOI18N
        limpar_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpar_button.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sorteioacamps/imagens/limpar_v2.jpg"))); // NOI18N
        limpar_button.setEnabled(false);
        getContentPane().add(limpar_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 90, 30));

        sort_number_1.setFont(new java.awt.Font("Showcard Gothic", 1, 56)); // NOI18N
        sort_number_1.setForeground(new java.awt.Color(0, 133, 178));
        sort_number_1.setText("???");
        getContentPane().add(sort_number_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        sort_number_2.setFont(new java.awt.Font("Showcard Gothic", 1, 56)); // NOI18N
        sort_number_2.setForeground(new java.awt.Color(0, 133, 178));
        sort_number_2.setText("???");
        getContentPane().add(sort_number_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        sort_number_3.setFont(new java.awt.Font("Showcard Gothic", 1, 56)); // NOI18N
        sort_number_3.setForeground(new java.awt.Color(0, 133, 178));
        sort_number_3.setText("???");
        getContentPane().add(sort_number_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        sort_number_4.setFont(new java.awt.Font("Showcard Gothic", 1, 56)); // NOI18N
        sort_number_4.setForeground(new java.awt.Color(0, 133, 178));
        sort_number_4.setText("???");
        getContentPane().add(sort_number_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        sort_number_5.setFont(new java.awt.Font("Showcard Gothic", 1, 56)); // NOI18N
        sort_number_5.setForeground(new java.awt.Color(0, 133, 178));
        sort_number_5.setText("???");
        getContentPane().add(sort_number_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        sort_number_6.setFont(new java.awt.Font("Showcard Gothic", 1, 56)); // NOI18N
        sort_number_6.setForeground(new java.awt.Color(0, 133, 178));
        sort_number_6.setText("???");
        getContentPane().add(sort_number_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        sort_number_7.setFont(new java.awt.Font("Showcard Gothic", 1, 56)); // NOI18N
        sort_number_7.setForeground(new java.awt.Color(0, 133, 178));
        sort_number_7.setText("???");
        getContentPane().add(sort_number_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        sort_number_8.setFont(new java.awt.Font("Showcard Gothic", 1, 56)); // NOI18N
        sort_number_8.setForeground(new java.awt.Color(0, 133, 178));
        sort_number_8.setText("???");
        getContentPane().add(sort_number_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        sort_number_9.setFont(new java.awt.Font("Showcard Gothic", 1, 56)); // NOI18N
        sort_number_9.setForeground(new java.awt.Color(0, 133, 178));
        sort_number_9.setText("???");
        getContentPane().add(sort_number_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        sort_number_10.setFont(new java.awt.Font("Showcard Gothic", 1, 56)); // NOI18N
        sort_number_10.setForeground(new java.awt.Color(0, 133, 178));
        sort_number_10.setText("???");
        getContentPane().add(sort_number_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        grade_sorteio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorteioacamps/imagens/grade.jpg"))); // NOI18N
        getContentPane().add(grade_sorteio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 520, 200));

        numeros_sorteados_label.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        numeros_sorteados_label.setForeground(new java.awt.Color(0, 133, 178));
        numeros_sorteados_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeros_sorteados_label.setText("numeros");
        getContentPane().add(numeros_sorteados_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 110, -1));

        voltar_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorteioacamps/imagens/voltar_v.jpg"))); // NOI18N
        voltar_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(voltar_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 90, 20));

        erro_variável.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        erro_variável.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(erro_variável, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 340, -1));

        sortear_tarefa_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorteioacamps/imagens/1.jpg"))); // NOI18N
        getContentPane().add(sortear_tarefa_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voltar_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SortearTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SortearTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SortearTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SortearTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SortearTarefa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel erro_variável;
    private javax.swing.JLabel grade_sorteio;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton limpar_button;
    private javax.swing.JLabel numeros_label;
    private javax.swing.JLabel numeros_sorteados_label;
    private javax.swing.JLabel sort_number_1;
    private javax.swing.JLabel sort_number_10;
    private javax.swing.JLabel sort_number_2;
    private javax.swing.JLabel sort_number_3;
    private javax.swing.JLabel sort_number_4;
    private javax.swing.JLabel sort_number_5;
    private javax.swing.JLabel sort_number_6;
    private javax.swing.JLabel sort_number_7;
    private javax.swing.JLabel sort_number_8;
    private javax.swing.JLabel sort_number_9;
    private javax.swing.JButton sortear_button;
    private javax.swing.JLabel sortear_label;
    private javax.swing.JLabel sortear_tarefa_background;
    private javax.swing.JButton voltar_button;
    // End of variables declaration//GEN-END:variables
}
